// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.1
//   protoc               v7.36.0
// source: voice_integrity.proto

/* eslint-disable */

export const protobufPackage = "";
