# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: voice_integrity.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'voice_integrity.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15voice_integrity.proto\x12\x0b\x61udiosentry\"G\n\nAudioChunk\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x03 \x01(\x03\"K\n\nRiskUpdate\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x05\x12\x18\n\x10layer2_triggered\x18\x03 \x01(\x08\"6\n\tAudioFile\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x15\n\rmetadata_json\x18\x02 \x01(\t\":\n\x11\x45nrollmentRequest\x12\x11\n\tcaller_id\x18\x01 \x01(\t\x12\x12\n\naudio_data\x18\x02 \x01(\x0c\"2\n\rEnrollmentAck\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\tcaller_id\x18\x02 \x01(\t\"9\n\x0f\x44\x65\x65pScanRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x15\n\rmetadata_json\x18\x02 \x01(\t\"D\n\x0fOverrideRequest\x12\x0f\n\x07\x63\x61ll_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x10\n\x08\x61gent_id\x18\x03 \x01(\t\".\n\x0bOverrideAck\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x63\x61ll_id\x18\x02 \x01(\t\"\x81\x01\n\nRiskResult\x12\x12\n\nrisk_score\x18\x01 \x01(\x05\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12:\n\x12recommended_action\x18\x03 \x01(\x0e\x32\x1e.audiosentry.RecommendedAction\x12\x13\n\x0bheatmap_png\x18\x04 \x01(\x0c*{\n\x11RecommendedAction\x12\x0b\n\x07\x41PPROVE\x10\x00\x12\x16\n\x12REQUIRE_MFA_STEPUP\x10\x01\x12\x15\n\x11INITIATE_CALLBACK\x10\x02\x12*\n&FREEZE_TRANSACTION_ESCALATE_SUPERVISOR\x10\x03\x32\xe9\x02\n\x15VoiceIntegrityService\x12\x43\n\x0bStreamAudio\x12\x17.audiosentry.AudioChunk\x1a\x17.audiosentry.RiskUpdate(\x01\x30\x01\x12>\n\x0b\x41nalyzeFile\x12\x16.audiosentry.AudioFile\x1a\x17.audiosentry.RiskResult\x12\x44\n\x06\x45nroll\x12\x1e.audiosentry.EnrollmentRequest\x1a\x1a.audiosentry.EnrollmentAck\x12\x41\n\x08\x44\x65\x65pScan\x12\x1c.audiosentry.DeepScanRequest\x1a\x17.audiosentry.RiskResult\x12\x42\n\x08Override\x12\x1c.audiosentry.OverrideRequest\x1a\x18.audiosentry.OverrideAckb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voice_integrity_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECOMMENDEDACTION']._serialized_start=665
  _globals['_RECOMMENDEDACTION']._serialized_end=788
  _globals['_AUDIOCHUNK']._serialized_start=38
  _globals['_AUDIOCHUNK']._serialized_end=109
  _globals['_RISKUPDATE']._serialized_start=111
  _globals['_RISKUPDATE']._serialized_end=186
  _globals['_AUDIOFILE']._serialized_start=188
  _globals['_AUDIOFILE']._serialized_end=242
  _globals['_ENROLLMENTREQUEST']._serialized_start=244
  _globals['_ENROLLMENTREQUEST']._serialized_end=302
  _globals['_ENROLLMENTACK']._serialized_start=304
  _globals['_ENROLLMENTACK']._serialized_end=354
  _globals['_DEEPSCANREQUEST']._serialized_start=356
  _globals['_DEEPSCANREQUEST']._serialized_end=413
  _globals['_OVERRIDEREQUEST']._serialized_start=415
  _globals['_OVERRIDEREQUEST']._serialized_end=483
  _globals['_OVERRIDEACK']._serialized_start=485
  _globals['_OVERRIDEACK']._serialized_end=531
  _globals['_RISKRESULT']._serialized_start=534
  _globals['_RISKRESULT']._serialized_end=663
  _globals['_VOICEINTEGRITYSERVICE']._serialized_start=791
  _globals['_VOICEINTEGRITYSERVICE']._serialized_end=1152
# @@protoc_insertion_point(module_scope)
