# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import voice_integrity_pb2 as voice__integrity__pb2

GRPC_GENERATED_VERSION = '1.66.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in voice_integrity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VoiceIntegrityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamAudio = channel.stream_stream(
                '/audiosentry.VoiceIntegrityService/StreamAudio',
                request_serializer=voice__integrity__pb2.AudioChunk.SerializeToString,
                response_deserializer=voice__integrity__pb2.RiskUpdate.FromString,
                _registered_method=True)
        self.AnalyzeFile = channel.unary_unary(
                '/audiosentry.VoiceIntegrityService/AnalyzeFile',
                request_serializer=voice__integrity__pb2.AudioFile.SerializeToString,
                response_deserializer=voice__integrity__pb2.RiskResult.FromString,
                _registered_method=True)
        self.Enroll = channel.unary_unary(
                '/audiosentry.VoiceIntegrityService/Enroll',
                request_serializer=voice__integrity__pb2.EnrollmentRequest.SerializeToString,
                response_deserializer=voice__integrity__pb2.EnrollmentAck.FromString,
                _registered_method=True)
        self.DeepScan = channel.unary_unary(
                '/audiosentry.VoiceIntegrityService/DeepScan',
                request_serializer=voice__integrity__pb2.DeepScanRequest.SerializeToString,
                response_deserializer=voice__integrity__pb2.RiskResult.FromString,
                _registered_method=True)
        self.Override = channel.unary_unary(
                '/audiosentry.VoiceIntegrityService/Override',
                request_serializer=voice__integrity__pb2.OverrideRequest.SerializeToString,
                response_deserializer=voice__integrity__pb2.OverrideAck.FromString,
                _registered_method=True)


class VoiceIntegrityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamAudio(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Enroll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeepScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Override(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceIntegrityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamAudio,
                    request_deserializer=voice__integrity__pb2.AudioChunk.FromString,
                    response_serializer=voice__integrity__pb2.RiskUpdate.SerializeToString,
            ),
            'AnalyzeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFile,
                    request_deserializer=voice__integrity__pb2.AudioFile.FromString,
                    response_serializer=voice__integrity__pb2.RiskResult.SerializeToString,
            ),
            'Enroll': grpc.unary_unary_rpc_method_handler(
                    servicer.Enroll,
                    request_deserializer=voice__integrity__pb2.EnrollmentRequest.FromString,
                    response_serializer=voice__integrity__pb2.EnrollmentAck.SerializeToString,
            ),
            'DeepScan': grpc.unary_unary_rpc_method_handler(
                    servicer.DeepScan,
                    request_deserializer=voice__integrity__pb2.DeepScanRequest.FromString,
                    response_serializer=voice__integrity__pb2.RiskResult.SerializeToString,
            ),
            'Override': grpc.unary_unary_rpc_method_handler(
                    servicer.Override,
                    request_deserializer=voice__integrity__pb2.OverrideRequest.FromString,
                    response_serializer=voice__integrity__pb2.OverrideAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'audiosentry.VoiceIntegrityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('audiosentry.VoiceIntegrityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceIntegrityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/audiosentry.VoiceIntegrityService/StreamAudio',
            voice__integrity__pb2.AudioChunk.SerializeToString,
            voice__integrity__pb2.RiskUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audiosentry.VoiceIntegrityService/AnalyzeFile',
            voice__integrity__pb2.AudioFile.SerializeToString,
            voice__integrity__pb2.RiskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Enroll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audiosentry.VoiceIntegrityService/Enroll',
            voice__integrity__pb2.EnrollmentRequest.SerializeToString,
            voice__integrity__pb2.EnrollmentAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeepScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audiosentry.VoiceIntegrityService/DeepScan',
            voice__integrity__pb2.DeepScanRequest.SerializeToString,
            voice__integrity__pb2.RiskResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Override(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/audiosentry.VoiceIntegrityService/Override',
            voice__integrity__pb2.OverrideRequest.SerializeToString,
            voice__integrity__pb2.OverrideAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
